### PR TITLE
added configurations for dbs

### PR DESCRIPTION
**Pull request by mayankagg9722**

### CODE REVIEW

**Comment by anuragsarkar97** [comment]
Ye to script hi likh diya pura 🤣

**Comment by anuragsarkar97** [comment]
We also need to discuss the structure of json...

**Comment by mayankagg9722** [comment]
> Ye to script hi likh diya pura 🤣

haan bro, everything that we have to done more than once has to be automated. 💯

**Comment by mayankagg9722** [comment]
> e also need to discuss the structure

Cool, lets discuss it today 👍

**Review by anuragsarkar97 — APPROVED** [review]
LGTM

**Pull request merged**
